# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
- label: Design Patterns
  items:
    - label: Adapter Design Pattern
      link: /design-patterns/adapter-design-pattern
- label: Practices
  items:
    - label: Code Readability
      link: /practices/code-readability
    - label: Collective Code Ownership
      link: /practices/collective-code-ownership
    - label: Continuous Integration
      link: /practices/continuous-integration
    - label: Dependency Injection
      link: /practices/dependency-injection
    - label: Dogfooding
      link: /practices/dogfooding
    - label: Know Where You Are Going
      link: /practices/know-where-you-are-going
    - label: Naming Things
      link: /practices/naming-things
- label: Principles
  items:
    - label: Boy Scout Rule
      link: /principles/boy-scout-rule
    - label: Dependency Inversion
      link: /principles/dependency-inversion-principle
    - label: Don't Repeat Yourself
      link: /principles/dont-repeat-yourself
    - label: Explicit Dependencies
      link: /principles/explicit-dependencies-principle
    - label: Hollywood
      link: /principles/hollywood-principle
    - label: Interface Segregation
      link: /principles/interface-segregation
    - label: Keep It Simple
      link: /principles/keep-it-simple
    - label: Liskov Substitution
      link: /principles/liskov-substitution-principle
- label: Antipatterns
  items:
    - label: Death March
      link: /antipatterns/death-march
- label: Values
  items:
    - label: Communication
      link: /values/communication
    - label: Courage
      link: /values/courage
    - label: Feedback
      link: /values/feedback
